# This file was *autogenerated* from the file 125.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10)
N = _sage_const_10 **_sage_const_8 
x = [i * (i + _sage_const_1 ) * (_sage_const_2  * i + _sage_const_1 ) / _sage_const_6  for i in (ellipsis_range(_sage_const_0  ,Ellipsis, int(sqrt(N) * _sage_const_2 )))]

def is_palin(x) :
    x = str(x)
    return list(x) == list(reversed(x))

s = set()
for i in range(len(x)) :
    for j in range(i - _sage_const_1 ) :
        if x[i] - x[j] <= N and is_palin(x[i] - x[j]) :
            s.add(x[i] - x[j])

print s, sum(s)
