# This file was *autogenerated* from the file 134.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1000000 = Integer(1000000); _sage_const_5 = Integer(5); _sage_const_1100000 = Integer(1100000)
ans = _sage_const_0 
q = _sage_const_0 
for p in primes(_sage_const_1100000 ) :
    if p > _sage_const_5  :
        l = len(str(q))
        x = CRT(q, _sage_const_0 , _sage_const_10 **l, p)
        ans += x
        # print p, q, x
    q = p
    if p > _sage_const_1000000  :
        break
print ans
