# This file was *autogenerated* from the file 17.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_900 = Integer(900); _sage_const_1000 = Integer(1000)
ans = -_sage_const_4 
with open("a000027.txt", "r") as fin :
    for i in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_1000 )) :
        x = fin.readline().split(' ')[_sage_const_2 ][:-_sage_const_1 ]
        ans += len(x)
        print x
print ans + _sage_const_3  * (_sage_const_900  - _sage_const_9 )
