# This file was *autogenerated* from the file 216.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_50000000 = Integer(50000000); _sage_const_100000 = Integer(100000)
ans = _sage_const_0 
for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_50000000 )) :
    if i % _sage_const_100000  == _sage_const_1  :
       print i
    if is_prime(i * i * _sage_const_2  - _sage_const_1 ) :
       ans += _sage_const_1 
print ans
