# This file was *autogenerated* from the file 22.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1)
with open("names.txt", "r") as fin :
    x = sorted(eval(fin.readline()))
print sum([idx * sum([ord(i) - ord('A') + _sage_const_1  for i in S]) for idx, S in enumerate(x, _sage_const_1 )])
