# This file was *autogenerated* from the file 240.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_70 = Integer(70); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20)
f = [[[_sage_const_0 ] * (_sage_const_20  + _sage_const_1 ) for i in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_70 ))] for j in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_12 ))]

def comb(n, m) :
    return factorial(n) / factorial(n - m) / factorial(m)

f[_sage_const_12 ][_sage_const_0 ][_sage_const_0 ] = _sage_const_1 
for i in range(_sage_const_12 , _sage_const_0 , -_sage_const_1 ) :
    for j in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_70 )) :
        for k in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_20 )) :
            for l in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_20  - k)) :
                s = j + (min(k + l, _sage_const_10 ) - min(k, _sage_const_10 )) * i
                if s > _sage_const_70  :
                    break
                f[i - _sage_const_1 ][s][k + l] += f[i][j][k] * comb(k + l, k)
print f[_sage_const_0 ][_sage_const_70 ][_sage_const_20 ]
