# This file was *autogenerated* from the file 301.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_30 )) :
    print i, fibonacci(i + _sage_const_2 )
print fibonacci(_sage_const_30  + _sage_const_2 )
