# This file was *autogenerated* from the file 34.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_145 = Integer(145); _sage_const_40585 = Integer(40585)# http://zh.wikipedia.org/wiki/145

print _sage_const_145  + _sage_const_40585 
