# This file was *autogenerated* from the file 345.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_15 = Integer(15)
n = _sage_const_15 
with open("345.in", "r") as fin :
    G = []
    for i in (ellipsis_range(_sage_const_1  ,Ellipsis, n)) :
        G += [map(int, fin.readline().split(' ')[:n])]

f = [_sage_const_0 ] * (_sage_const_1  << n)
for S in (ellipsis_range(_sage_const_0  ,Ellipsis, (_sage_const_1  << n) - _sage_const_1 )) :
    x = _sage_const_0 
    for i in (ellipsis_range(_sage_const_0  ,Ellipsis, (n - _sage_const_1 ))) :
        if (S >> i) & _sage_const_1  :
            x += _sage_const_1 
    for y in (ellipsis_range(_sage_const_0  ,Ellipsis, (n - _sage_const_1 ))) :
        if not ((S >> y) & _sage_const_1 ) :
            f[S | _sage_const_1  << y] = max(f[S | _sage_const_1  << y], f[S] + G[x][y])
print f[(_sage_const_1  << n) - _sage_const_1 ]
