# This file was *autogenerated* from the file 37.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_1 = Integer(1)
ans = _sage_const_0 

def dfs(x) :
    global ans
    if not is_prime(x) :
        return 
    b = True
    p = _sage_const_10 
    while p <= x :
        if not is_prime(x % p) :
            b = False
            break
        p *= _sage_const_10 
        
    if b and x > _sage_const_10  :
        print x
        ans += x
    for i in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_9 )) :
        dfs(x * _sage_const_10  + i)

for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_9 )) :
    dfs(i)
print ans
