# This file was *autogenerated* from the file 38.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9)
def chk(x) :
    s = str(x)
    y = x // _sage_const_10 
    while y > _sage_const_0  :
        S = ""
        cnt = _sage_const_1 
        while len(S) < len(s) :
            S += str(cnt * y)
            cnt += _sage_const_1 
        
        if S == s :
            print x, y
            return True
        y = y // _sage_const_10 
    return False

ans = _sage_const_0 
for x in permutations((ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_9 ))) :
    v = sum([j * _sage_const_10  ** i for i, j in enumerate(x)])
    if chk(v) :
        ans = max(ans, v)
