# This file was *autogenerated* from the file 402.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10)# def calc() :
    

# for i in [0 .. 23] :
#     ans += calc(i, fibonacci(i) % 6)

for n in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_10 )) :
    ans = _sage_const_0 
    for a in (ellipsis_range(_sage_const_1  ,Ellipsis, n)) :
        for b in (ellipsis_range(_sage_const_1  ,Ellipsis, n)) :
            for c in (ellipsis_range(_sage_const_1  ,Ellipsis, n)) :
                t = _sage_const_1 
                if (a + b + c) % _sage_const_2  == _sage_const_1  :
                    t *= _sage_const_2 
                    if a % _sage_const_2  == _sage_const_0  and b % _sage_const_2  == _sage_const_1  and (a + b + c + _sage_const_1 ) % _sage_const_4  == _sage_const_0  :
                        t *= _sage_const_2 
                if b % _sage_const_3  == _sage_const_2  and (a + c) % _sage_const_3  == _sage_const_0  :
                    t *= _sage_const_3 
                ans += t
    print ans
