# This file was *autogenerated* from the file 41.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9)
ans = _sage_const_0 
for T in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_9 )) :
    for x in permutations((ellipsis_range(_sage_const_1  ,Ellipsis, T))) :
        s = sum([i * _sage_const_10  ** j for j, i in enumerate(x)])
        if is_prime(s) :
            ans = max(ans, s)
            print s, i, ans
