# This file was *autogenerated* from the file 43.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10)
a = primes_first_n(_sage_const_7 )
ans = _sage_const_0 
for T in permutations((ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_9 ))) :
    if T[_sage_const_0 ] == _sage_const_0  :
        continue
    b = True
    for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_7 )) :
        s = _sage_const_100  * T[i] + _sage_const_10  * T[i + _sage_const_1 ] + T[i + _sage_const_2 ]
        if s % a[i - _sage_const_1 ] != _sage_const_0  :
            b = False
            break
    # print x

    if b :
        x = sum([i * _sage_const_10 **(_sage_const_9  - j) for j, i in enumerate(T)])
        print x
        ans += x
print ans
