# This file was *autogenerated* from the file 436.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20)# print n(20/17, digits = 20)
t = var('t')

P = e - e**(_sage_const_1  - x) # pdf of player 1
print integral(P * x, x, _sage_const_0 , _sage_const_1 ).n(_sage_const_30 )

Q = integral((e - _sage_const_1  - t) * e**t, t, _sage_const_1  - x, _sage_const_1 )
print integral(Q * x, x, _sage_const_0 , _sage_const_1 ).n(_sage_const_30 )

ans = integral(Q * integral(P, x, _sage_const_0 , x), x, _sage_const_0 , _sage_const_1 )
print ans, ans.n(digits = _sage_const_20 )
