# This file was *autogenerated* from the file 437.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10)
ans = _sage_const_0 
lx = _sage_const_0 
for p in primes(_sage_const_10 **_sage_const_8 ) :
    if kronecker(_sage_const_5 , p) == -_sage_const_1  :
        continue
    if p > lx :
        print p
        lx += _sage_const_10 **_sage_const_5 
    R = Integers(p)
    m, d = R(-_sage_const_1 ) / _sage_const_2 , R(_sage_const_5 ).sqrt() / _sage_const_2 
    x, y = m + d, m - d
    if multiplicative_order(x) == p - _sage_const_1  or multiplicative_order(y) == p - _sage_const_1  :
        ans += p
        # print p
print ans
