# This file was *autogenerated* from the file 457.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_9470107 = Integer(9470107); _sage_const_10000 = Integer(10000); _sage_const_13 = Integer(13); _sage_const_2255375755669783454 = Integer(2255375755669783454); _sage_const_10 = Integer(10)
from gc import collect

ans = _sage_const_2255375755669783454 
lmt = _sage_const_9470107 
lx = _sage_const_0 
for p in primes(_sage_const_10 **_sage_const_7 ) :
    if p <= lmt :
        continue
    x = p * p
    if legendre_symbol(_sage_const_13 , p) == _sage_const_1  :
        y1 = Integers(x)(_sage_const_13 ).sqrt()
        y2 = x - y1
        cur = min((_sage_const_3  + y1) / _sage_const_2 , (_sage_const_3  - y1) / _sage_const_2 , (_sage_const_3  + y2) / _sage_const_2 , (_sage_const_3  - y2) / _sage_const_2 )
        ans += int(cur)
        if p // _sage_const_10000  != lx :
            lx = p // _sage_const_10000 
            print p, cur, ans
print ans
