# This file was *autogenerated* from the file 465.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
def f(n) :
    t = _sage_const_0 
    for i in (ellipsis_range(_sage_const_1  ,Ellipsis, n)) :
        if n % i == _sage_const_0  :
            t += euler_phi(i) * n / i
    return t

ans = _sage_const_0 
for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_100 )) :
    ans += f(i)
    print ans, f(i), euler_phi(i)
