# This file was *autogenerated* from the file 80.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_100 = Integer(100); _sage_const_108 = Integer(108); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_99 = Integer(99)
ans = _sage_const_0 
for i in (ellipsis_range(_sage_const_1  ,Ellipsis, _sage_const_100 )) :
    a = n(sqrt(i), digits = _sage_const_108 )
    if floor(a) == a :
        continue
    a = str(a)
    if len(a) < _sage_const_100  :
        continue
    a = ''.join(a.split('.'))
    for j in (ellipsis_range(_sage_const_0  ,Ellipsis, _sage_const_99 )) :
        ans += int(a[j])
print ans
