# This file was *autogenerated* from the file 95.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5916 = Integer(5916)
LMT = _sage_const_10 **_sage_const_6 
f, g = dict(), dict()

def dfs(x, d) :
    print x, sigma(x) - x
    if x > LMT or x <= _sage_const_1  :
        return -_sage_const_1 
    if x in g :
        return d - g[x]
    if x in f :
        return f[x]
    g[x] = d
    f[x] = dfs(sigma(x) - x, d + _sage_const_1 )
    del g[x]
    return f[x]

dfs(_sage_const_5916 , _sage_const_0 )
# ans = 0
# for i in [1 .. LMT] :
#     x = dfs(i, 0)
#     if x > ans :
#         ans = x
#         print ans, i
