# This file was *autogenerated* from the file 96.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_50 = Integer(50)
ans = _sage_const_0 
with open("sudoku.txt", "r") as fin :
    for _ in range(_sage_const_50 ) :
        fin.readline()
        x = []
        for i in range(_sage_const_9 ) :
            x += [list(map(int, list(fin.readline())[:_sage_const_9 ]))]
        t = sudoku(matrix(x))[_sage_const_0 ]
        ans += t[_sage_const_0 ] * _sage_const_100  + t[_sage_const_1 ] * _sage_const_10  + t[_sage_const_2 ]
print ans
